# Generated by Django 6.0.6 on 2026-08-26 12:39

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='낸 달란트')),
                ('code', models.CharField(default=core.models.new_purchase_code, max_length=4, verbose_name='확인 번호')),
                ('status', models.CharField(choices=[('pending', '확인 대기'), ('done', '확인 완료'), ('refunded', '취소됨')], db_index=True, default='pending', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='낸 시각')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='확인·취소 시각')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_purchases', to=settings.AUTH_USER_MODEL, verbose_name='처리한 상인')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='낸 학생')),
            ],
            options={
                'verbose_name': '달란트 결제',
                'verbose_name_plural': '달란트 결제 내역',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('classic', '기본'), ('market', '달란트 시장')], default='classic', max_length=10, verbose_name='운영 모드')),
                ('event_host', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='암송 이벤트 담당')),
            ],
            options={
                'verbose_name': '운영 설정',
                'verbose_name_plural': '운영 설정',
            },
        ),
    ]
