# Generated by Django 6.0.6 on 2026-08-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_purchase_siteconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', '학생'), ('teacher', '선생님'), ('merchant', '상인'), ('admin', '관리자')], default='student', max_length=10, verbose_name='역할'),
        ),
    ]
